openapi: 3.0.0

info:
  title: AlienVault
  description: This plugin provides the functionality to fetch recent pulse activity from AlienVault.
  version: "1.0.0"

servers:
  - url: https://otx.alienvault.com/api/v1

paths:
  /pulses/activity:
    get:
      operationId: GetRecentPulseActivity
      summary: Get recent threat pulse activity from AlienVault OTX.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
      security:
        - apiKeyAuth: []

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-OTX-API-KEY
